backend: 
  name: github
  repo: havardob/noel
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: img
collections: 
 - name: 'post'
   label: 'Posts'
   folder: 'posts'
   create: true
   fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Fact", name: "fact", widget: "markdown"}
      - {label: "Badge", name: "badge", widget: "boolean"}